// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OfferApiService.Models;

#nullable disable

namespace OfferApiService.Migrations
{
    [DbContext(typeof(OfferContext))]
    [Migration("20251126092830_InitialWithSeeds")]
    partial class InitialWithSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OfferApiService.Models.BookedDate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("OfferId");

                    b.ToTable("BookedDates", (string)null);
                });

            modelBuilder.Entity("OfferApiService.Models.Offer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("AllowChildren")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowPets")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowSmoking")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("CheckInTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("CheckOutTime")
                        .HasColumnType("interval");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinRentDays")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PricePerMonth")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PricePerWeek")
                        .HasColumnType("numeric");

                    b.Property<int>("RentObjId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Offers", (string)null);
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            CountryId = 1,
                            Title = "New York"
                        },
                        new
                        {
                            id = 2,
                            CountryId = 1,
                            Title = "Los Angeles"
                        },
                        new
                        {
                            id = 3,
                            CountryId = 1,
                            Title = "Chicago"
                        },
                        new
                        {
                            id = 4,
                            CountryId = 2,
                            Title = "Berlin"
                        },
                        new
                        {
                            id = 5,
                            CountryId = 2,
                            Title = "Munich"
                        },
                        new
                        {
                            id = 6,
                            CountryId = 2,
                            Title = "Hamburg"
                        },
                        new
                        {
                            id = 7,
                            CountryId = 3,
                            Title = "Paris"
                        },
                        new
                        {
                            id = 8,
                            CountryId = 3,
                            Title = "Lyon"
                        },
                        new
                        {
                            id = 9,
                            CountryId = 3,
                            Title = "Marseille"
                        },
                        new
                        {
                            id = 10,
                            CountryId = 4,
                            Title = "London"
                        },
                        new
                        {
                            id = 11,
                            CountryId = 4,
                            Title = "Manchester"
                        },
                        new
                        {
                            id = 12,
                            CountryId = 4,
                            Title = "Birmingham"
                        },
                        new
                        {
                            id = 13,
                            CountryId = 5,
                            Title = "Madrid"
                        },
                        new
                        {
                            id = 14,
                            CountryId = 5,
                            Title = "Barcelona"
                        },
                        new
                        {
                            id = 15,
                            CountryId = 5,
                            Title = "Valencia"
                        },
                        new
                        {
                            id = 16,
                            CountryId = 6,
                            Title = "Warsaw"
                        },
                        new
                        {
                            id = 17,
                            CountryId = 6,
                            Title = "Kraków"
                        },
                        new
                        {
                            id = 18,
                            CountryId = 6,
                            Title = "Poznań"
                        });
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            Title = "United States"
                        },
                        new
                        {
                            id = 2,
                            Title = "Germany"
                        },
                        new
                        {
                            id = 3,
                            Title = "France"
                        },
                        new
                        {
                            id = 4,
                            Title = "United Kingdom"
                        },
                        new
                        {
                            id = 5,
                            Title = "Spain"
                        },
                        new
                        {
                            id = 6,
                            Title = "Poland"
                        });
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.ParamItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ParamItems", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            CategoryId = 1,
                            Title = "Free WiFi",
                            ValueType = 1
                        },
                        new
                        {
                            id = 2,
                            CategoryId = 1,
                            Title = "Non‑smoking rooms",
                            ValueType = 1
                        },
                        new
                        {
                            id = 3,
                            CategoryId = 1,
                            Title = "Air conditioning",
                            ValueType = 1
                        },
                        new
                        {
                            id = 4,
                            CategoryId = 1,
                            Title = "Heating",
                            ValueType = 1
                        },
                        new
                        {
                            id = 5,
                            CategoryId = 1,
                            Title = "Pets allowed",
                            ValueType = 1
                        },
                        new
                        {
                            id = 6,
                            CategoryId = 2,
                            Title = "Elevator",
                            ValueType = 1
                        },
                        new
                        {
                            id = 7,
                            CategoryId = 2,
                            Title = "24‑hour front desk",
                            ValueType = 1
                        },
                        new
                        {
                            id = 8,
                            CategoryId = 2,
                            Title = "Security",
                            ValueType = 1
                        },
                        new
                        {
                            id = 9,
                            CategoryId = 3,
                            Title = "Parking",
                            ValueType = 1
                        },
                        new
                        {
                            id = 10,
                            CategoryId = 4,
                            Title = "Garden",
                            ValueType = 1
                        },
                        new
                        {
                            id = 11,
                            CategoryId = 4,
                            Title = "Terrace",
                            ValueType = 1
                        },
                        new
                        {
                            id = 12,
                            CategoryId = 4,
                            Title = "BBQ / Picnic area",
                            ValueType = 1
                        },
                        new
                        {
                            id = 13,
                            CategoryId = 5,
                            Title = "Airport shuttle",
                            ValueType = 1
                        },
                        new
                        {
                            id = 14,
                            CategoryId = 5,
                            Title = "Laundry",
                            ValueType = 1
                        },
                        new
                        {
                            id = 15,
                            CategoryId = 5,
                            Title = "Dry cleaning",
                            ValueType = 1
                        },
                        new
                        {
                            id = 16,
                            CategoryId = 5,
                            Title = "Concierge",
                            ValueType = 1
                        },
                        new
                        {
                            id = 17,
                            CategoryId = 6,
                            Title = "Restaurant",
                            ValueType = 1
                        },
                        new
                        {
                            id = 18,
                            CategoryId = 6,
                            Title = "Bar",
                            ValueType = 1
                        },
                        new
                        {
                            id = 19,
                            CategoryId = 6,
                            Title = "Breakfast included",
                            ValueType = 1
                        },
                        new
                        {
                            id = 20,
                            CategoryId = 7,
                            Title = "Fitness center",
                            ValueType = 1
                        },
                        new
                        {
                            id = 21,
                            CategoryId = 7,
                            Title = "Sauna",
                            ValueType = 1
                        },
                        new
                        {
                            id = 22,
                            CategoryId = 7,
                            Title = "Outdoor pool",
                            ValueType = 1
                        },
                        new
                        {
                            id = 23,
                            CategoryId = 7,
                            Title = "Indoor pool",
                            ValueType = 1
                        },
                        new
                        {
                            id = 24,
                            CategoryId = 8,
                            Title = "Shower",
                            ValueType = 1
                        },
                        new
                        {
                            id = 25,
                            CategoryId = 8,
                            Title = "Bathtub",
                            ValueType = 1
                        },
                        new
                        {
                            id = 26,
                            CategoryId = 8,
                            Title = "Hair dryer",
                            ValueType = 1
                        },
                        new
                        {
                            id = 27,
                            CategoryId = 8,
                            Title = "TV",
                            ValueType = 1
                        },
                        new
                        {
                            id = 28,
                            CategoryId = 8,
                            Title = "Minibar",
                            ValueType = 1
                        },
                        new
                        {
                            id = 29,
                            CategoryId = 8,
                            Title = "Safe",
                            ValueType = 1
                        });
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.ParamsCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ParamsCategories", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            Title = "General"
                        },
                        new
                        {
                            id = 2,
                            Title = "Building"
                        },
                        new
                        {
                            id = 3,
                            Title = "Location"
                        },
                        new
                        {
                            id = 4,
                            Title = "Outdoors"
                        },
                        new
                        {
                            id = 5,
                            Title = "Services"
                        },
                        new
                        {
                            id = 6,
                            Title = "Food & Drink"
                        },
                        new
                        {
                            id = 7,
                            Title = "Wellness & Recreation"
                        },
                        new
                        {
                            id = 8,
                            Title = "Room Facilities"
                        });
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.RentObj", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<int>("BathroomCount")
                        .HasColumnType("integer");

                    b.Property<int>("BedroomsCount")
                        .HasColumnType("integer");

                    b.Property<int>("BedsCount")
                        .HasColumnType("integer");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<bool>("HasBabyCrib")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("RentObjType")
                        .HasColumnType("integer");

                    b.Property<int>("RoomCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalFloors")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CityId");

                    b.ToTable("RentObjects", (string)null);
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.RentObjImage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("RentObjId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("RentObjId");

                    b.ToTable("RentObjImage");
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.RentObjParamValue", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("ParamItemId")
                        .HasColumnType("integer");

                    b.Property<int>("RentObjId")
                        .HasColumnType("integer");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean");

                    b.Property<int?>("ValueInt")
                        .HasColumnType("integer");

                    b.Property<string>("ValueString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("ParamItemId");

                    b.HasIndex("RentObjId");

                    b.ToTable("RentObjParamValues", (string)null);
                });

            modelBuilder.Entity("OfferApiService.Models.BookedDate", b =>
                {
                    b.HasOne("OfferApiService.Models.Offer", "Offer")
                        .WithMany("BookedDates")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.City", b =>
                {
                    b.HasOne("OfferApiService.Models.RentObject.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.ParamItem", b =>
                {
                    b.HasOne("OfferApiService.Models.RentObject.ParamsCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.RentObj", b =>
                {
                    b.HasOne("OfferApiService.Models.RentObject.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.RentObjImage", b =>
                {
                    b.HasOne("OfferApiService.Models.RentObject.RentObj", "RentObj")
                        .WithMany("Images")
                        .HasForeignKey("RentObjId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentObj");
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.RentObjParamValue", b =>
                {
                    b.HasOne("OfferApiService.Models.RentObject.ParamItem", "ParamItem")
                        .WithMany("RentObjValues")
                        .HasForeignKey("ParamItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfferApiService.Models.RentObject.RentObj", "RentObj")
                        .WithMany("ParamValues")
                        .HasForeignKey("RentObjId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParamItem");

                    b.Navigation("RentObj");
                });

            modelBuilder.Entity("OfferApiService.Models.Offer", b =>
                {
                    b.Navigation("BookedDates");
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.ParamItem", b =>
                {
                    b.Navigation("RentObjValues");
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.ParamsCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OfferApiService.Models.RentObject.RentObj", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ParamValues");
                });
#pragma warning restore 612, 618
        }
    }
}
