import { Booking, Offer, OwnerProfile, Payment, Review, Room, User } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'demo@oselya.app',
    name: 'Demo User',
    role: 'user',
    phone: '+380501111111',
  },
  {
    id: 'owner-1',
    email: 'owner@oselya.app',
    name: 'Owner One',
    role: 'owner',
    phone: '+380661112222',
  },
  {
    id: 'owner-2',
    email: 'owner2@oselya.app',
    name: 'Owner Two',
    role: 'owner',
    phone: '+380631112233',
    isBlocked: true,
  },
  {
    id: 'admin-1',
    email: 'admin@oselya.app',
    name: 'Super Admin',
    role: 'admin',
    phone: '+380931114444',
  },
];

export const mockUser = mockUsers[0];

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    offerId: 'offer-1',
    bookingId: 'booking-1',
    userName: 'Катерина',
    rating: 5,
    comment: 'Чисто, тихо и в центре. Хозяин встретил вовремя.',
    createdAt: '2024-03-12',
    reply: 'Спасибо за отзыв! Всегда рады.',
    status: 'published',
  },
  {
    id: 'review-2',
    offerId: 'offer-1',
    bookingId: 'booking-1',
    userName: 'Олег',
    rating: 4,
    comment: 'Отличное расположение, но парковка платная.',
    createdAt: '2024-02-05',
    status: 'published',
  },
  {
    id: 'review-3',
    offerId: 'offer-2',
    bookingId: 'booking-2',
    userName: 'Мария',
    rating: 5,
    comment: 'Вид на море — космос. Терраса огромная.',
    createdAt: '2024-01-18',
    status: 'published',
  },
  {
    id: 'review-4',
    offerId: 'offer-3',
    bookingId: 'booking-3',
    userName: 'Антон',
    rating: 4,
    comment: 'Быстрый Wi‑Fi и рядом метро. Немного шумно вечером.',
    createdAt: '2024-03-02',
    status: 'published',
  },
  {
    id: 'review-5',
    offerId: 'offer-4',
    userName: 'Светлана',
    rating: 5,
    comment: 'Идеально для семьи, двор закрыт, детская площадка.',
    createdAt: '2024-02-22',
    status: 'published',
  },
];

const ownerProfiles: Record<string, OwnerProfile> = {
  'owner-1': {
    id: 'owner-1',
    name: 'Василина',
    avatarUrl: 'https://picsum.photos/seed/owner1/600/400',
    reviewsCount: 55,
    rating: 9.7,
    yearsHosting: 1,
    languages: 'Розмовляє на українській та англійській мовах',
  },
  'owner-2': {
    id: 'owner-2',
    name: 'Олена',
    avatarUrl: 'https://picsum.photos/seed/owner2/600/400',
    reviewsCount: 28,
    rating: 9.1,
    yearsHosting: 2,
    languages: 'Розмовляє українською та англійською',
  },
  'owner-3': {
    id: 'owner-3',
    name: 'Ірина',
    avatarUrl: 'https://picsum.photos/seed/owner3/600/400',
    reviewsCount: 19,
    rating: 8.9,
    yearsHosting: 2,
    languages: 'Розмовляє українською',
  },
  'owner-4': {
    id: 'owner-4',
    name: 'Марія',
    avatarUrl: 'https://picsum.photos/seed/owner4/600/400',
    reviewsCount: 12,
    rating: 8.6,
    yearsHosting: 1,
    languages: 'Розмовляє українською та польською',
  },
  'owner-5': {
    id: 'owner-5',
    name: 'Назар',
    avatarUrl: 'https://picsum.photos/seed/owner5/600/400',
    reviewsCount: 33,
    rating: 9.3,
    yearsHosting: 3,
    languages: 'Розмовляє українською та англійською',
  },
  'owner-6': {
    id: 'owner-6',
    name: 'Соломія',
    avatarUrl: 'https://picsum.photos/seed/owner6/600/400',
    reviewsCount: 16,
    rating: 8.7,
    yearsHosting: 1,
    languages: 'Розмовляє українською',
  },
  'owner-7': {
    id: 'owner-7',
    name: 'Богдан',
    avatarUrl: 'https://picsum.photos/seed/owner7/600/400',
    reviewsCount: 21,
    rating: 8.8,
    yearsHosting: 2,
    languages: 'Розмовляє українською та англійською',
  },
  'owner-8': {
    id: 'owner-8',
    name: 'Катерина',
    avatarUrl: 'https://picsum.photos/seed/owner8/600/400',
    reviewsCount: 14,
    rating: 8.5,
    yearsHosting: 1,
    languages: 'Розмовляє українською',
  },
};

const defaultOwner = (ownerId: string): OwnerProfile => ({
  id: ownerId,
  name: 'Власник',
  avatarUrl: 'https://picsum.photos/seed/owner-default/600/400',
  reviewsCount: 0,
  rating: 0,
  yearsHosting: 0,
  languages: 'Розмовляє українською',
});

const defaultRooms = (offer: Offer, index: number): Room[] => {
  const basePrice = Math.max(offer.pricePerNight, 500);
  return [
    {
      id: `room-${offer.id}-1`,
      title:
        'Покращенний двомісний номер з одним ліжком 1 кімната 1 двоспальне ліжко ванна кімната',
      price: basePrice + 250,
      image: offer.images?.[0] ?? `https://picsum.photos/seed/room-${index}-1/600/400`,
    },
    {
      id: `room-${offer.id}-2`,
      title:
        'Покращенний двомісний номер з одним ліжком 1 кімната 1 двоспальне ліжко ванна кімната',
      price: basePrice + 450,
      image: offer.images?.[1] ?? `https://picsum.photos/seed/room-${index}-2/600/400`,
    },
  ];
};

const baseOffers: Offer[] = [
  {
    id: 'offer-1',
    title: 'Уютные апартаменты в центре',
    description: 'Просторные апартаменты рядом с набережной и кафе.',
    city: { id: 'city-1', name: 'Одесса', country: 'Украина' },
    address: 'Дерибасовская, 1',
    pricePerNight: 120,
    rating: 4.7,
    guests: 2,
    bedrooms: 1,
    amenities: ['Wi-Fi', 'Кондиционер', 'Парковка', 'Кухня'],
    images: ['https://picsum.photos/seed/offer1/600/400'],
    ownerId: 'owner-1',
    isActive: true,
    type: 'apartment',
    highlights: ['Бесплатная отмена', 'Без предоплаты'],
    reviews: mockReviews.filter((r) => r.offerId === 'offer-1'),
  },
  {
    id: 'offer-2',
    title: 'Домик у моря',
    description: 'Панорамный вид на море, терраса и гриль.',
    city: { id: 'city-2', name: 'Батуми', country: 'Грузия' },
    address: 'Набережная, 25',
    pricePerNight: 90,
    rating: 4.5,
    guests: 4,
    bedrooms: 2,
    amenities: ['Wi-Fi', 'Парковка', 'Кухня'],
    images: ['https://picsum.photos/seed/offer2/600/400'],
    ownerId: 'owner-1',
    isActive: true,
    type: 'house',
    highlights: ['Оплата на месте'],
    reviews: mockReviews.filter((r) => r.offerId === 'offer-2'),
  },
  {
    id: 'offer-3',
    title: 'Современный лофт',
    description: 'Высокие потолки, панорамные окна и вид на город.',
    city: { id: 'city-3', name: 'Киев', country: 'Украина' },
    address: 'Сагайдачного, 12',
    pricePerNight: 150,
    rating: 4.6,
    guests: 3,
    bedrooms: 1,
    amenities: ['Wi-Fi', 'Кондиционер', 'Кухня', 'Балкон'],
    images: ['https://picsum.photos/seed/offer3/600/400'],
    ownerId: 'owner-2',
    isActive: true,
    type: 'apartment',
    highlights: ['Бесплатная отмена'],
    reviews: mockReviews.filter((r) => r.offerId === 'offer-3'),
  },
  {
    id: 'offer-4',
    title: 'Загородный дом с садом',
    description: 'Большой участок, мангал и собственная баня.',
    city: { id: 'city-1', name: 'Одесса', country: 'Украина' },
    address: 'Лесная, 8',
    pricePerNight: 110,
    rating: 4.8,
    guests: 6,
    bedrooms: 3,
    amenities: ['Wi-Fi', 'Парковка', 'Кухня', 'Стиральная машина'],
    images: ['https://picsum.photos/seed/offer4/600/400'],
    ownerId: 'owner-2',
    isActive: true,
    type: 'house',
    highlights: ['Семейный вариант', 'Оплата на месте'],
    reviews: mockReviews.filter((r) => r.offerId === 'offer-4'),
  },
  {
    id: 'offer-5',
    title: 'Апартаменти біля Ринку',
    description: 'Квартира з видом на площу Ринок.',
    city: { id: 'city-3', name: 'Львів', country: 'Україна' },
    address: 'Площа Ринок, 10',
    pricePerNight: 1450,
    rating: 4.9,
    guests: 2,
    bedrooms: 1,
    amenities: ['Wi-Fi', 'Кухня', 'Балкон'],
    images: ['https://picsum.photos/seed/offer5/600/400'],
    ownerId: 'owner-3',
    isActive: true,
    type: 'apartment',
    highlights: ['Безкоштовна відміна'],
    reviews: [],
  },
  {
    id: 'offer-6',
    title: 'Studio Center',
    description: 'Невелика студія у центрі міста.',
    city: { id: 'city-3', name: 'Львів', country: 'Україна' },
    address: 'Проспект Свободи, 20',
    pricePerNight: 980,
    rating: 4.4,
    guests: 2,
    bedrooms: 1,
    amenities: ['Wi-Fi', 'Праска'],
    images: ['https://picsum.photos/seed/offer6/600/400'],
    ownerId: 'owner-3',
    isActive: true,
    type: 'apartment',
    highlights: ['Оплата на місці'],
    reviews: [],
  },
  {
    id: 'offer-7',
    title: 'Сімейний будинок',
    description: 'Просторий будинок з терасою та кухнею.',
    city: { id: 'city-1', name: 'Львів', country: 'Україна' },
    address: 'Зелена, 35',
    pricePerNight: 2100,
    rating: 4.6,
    guests: 6,
    bedrooms: 3,
    amenities: ['Wi-Fi', 'Кухня', 'Тераса', 'Парковка'],
    images: ['https://picsum.photos/seed/offer7/600/400'],
    ownerId: 'owner-4',
    isActive: true,
    type: 'house',
    highlights: ['Безкоштовна відміна'],
    reviews: [],
  },
  {
    id: 'offer-8',
    title: 'Апартаменти біля парку',
    description: 'Затишна квартира поруч із парком.',
    city: { id: 'city-3', name: 'Львів', country: 'Україна' },
    address: 'Личаківська, 5',
    pricePerNight: 1250,
    rating: 4.3,
    guests: 3,
    bedrooms: 1,
    amenities: ['Wi-Fi', 'Кухня', 'Кондиціонер'],
    images: ['https://picsum.photos/seed/offer8/600/400'],
    ownerId: 'owner-4',
    isActive: true,
    type: 'apartment',
    highlights: ['Оплата зараз'],
    reviews: [],
  },
  {
    id: 'offer-9',
    title: 'Центральні апартаменти',
    description: 'Комфортні апартаменти у центрі.',
    city: { id: 'city-3', name: 'Львів', country: 'Україна' },
    address: 'Вірменська, 12',
    pricePerNight: 1600,
    rating: 4.8,
    guests: 4,
    bedrooms: 2,
    amenities: ['Wi-Fi', 'Кухня', 'Пральна машина'],
    images: ['https://picsum.photos/seed/offer9/600/400'],
    ownerId: 'owner-5',
    isActive: true,
    type: 'apartment',
    highlights: ['Безкоштовна відміна'],
    reviews: [],
  },
  {
    id: 'offer-10',
    title: 'Лофт з балконом',
    description: 'Світлий лофт з балконом.',
    city: { id: 'city-3', name: 'Львів', country: 'Україна' },
    address: 'Городоцька, 80',
    pricePerNight: 1350,
    rating: 4.5,
    guests: 2,
    bedrooms: 1,
    amenities: ['Wi-Fi', 'Балкон', 'Праска'],
    images: ['https://picsum.photos/seed/offer10/600/400'],
    ownerId: 'owner-5',
    isActive: true,
    type: 'apartment',
    highlights: ['Оплата на місці'],
    reviews: [],
  },
  {
    id: 'offer-11',
    title: 'Апартаменти для бізнесу',
    description: 'Є робочий стіл та швидкий інтернет.',
    city: { id: 'city-3', name: 'Львів', country: 'Україна' },
    address: 'Сахарова, 14',
    pricePerNight: 1550,
    rating: 4.7,
    guests: 2,
    bedrooms: 1,
    amenities: ['Wi-Fi', 'Робочий стіл', 'Кондиціонер'],
    images: ['https://picsum.photos/seed/offer11/600/400'],
    ownerId: 'owner-6',
    isActive: true,
    type: 'apartment',
    highlights: ['Оплата зараз'],
    reviews: [],
  },
  {
    id: 'offer-12',
    title: 'Будинок з терасою',
    description: 'Тераса та місце для відпочинку.',
    city: { id: 'city-3', name: 'Львів', country: 'Україна' },
    address: 'Наукова, 3',
    pricePerNight: 2300,
    rating: 4.4,
    guests: 5,
    bedrooms: 2,
    amenities: ['Wi-Fi', 'Тераса', 'Парковка'],
    images: ['https://picsum.photos/seed/offer12/600/400'],
    ownerId: 'owner-6',
    isActive: true,
    type: 'house',
    highlights: ['Безкоштовна відміна'],
    reviews: [],
  },
  {
    id: 'offer-13',
    title: 'Апартаменти біля вокзалу',
    description: 'Зручне розташування поруч з вокзалом.',
    city: { id: 'city-3', name: 'Львів', country: 'Україна' },
    address: 'Чернівецька, 1',
    pricePerNight: 980,
    rating: 4.1,
    guests: 2,
    bedrooms: 1,
    amenities: ['Wi-Fi', 'Кухня'],
    images: ['https://picsum.photos/seed/offer13/600/400'],
    ownerId: 'owner-7',
    isActive: true,
    type: 'apartment',
    highlights: ['Оплата на місці'],
    reviews: [],
  },
  {
    id: 'offer-14',
    title: 'Комфортна квартира',
    description: 'Затишна квартира з усім необхідним.',
    city: { id: 'city-3', name: 'Львів', country: 'Україна' },
    address: 'Шевченка, 45',
    pricePerNight: 1200,
    rating: 4.2,
    guests: 3,
    bedrooms: 1,
    amenities: ['Wi-Fi', 'Пральна машина'],
    images: ['https://picsum.photos/seed/offer14/600/400'],
    ownerId: 'owner-7',
    isActive: true,
    type: 'apartment',
    highlights: ['Оплата зараз'],
    reviews: [],
  },
  {
    id: 'offer-15',
    title: 'Апартаменти з кухнею',
    description: 'Ідеально для довгих поїздок.',
    city: { id: 'city-3', name: 'Львів', country: 'Україна' },
    address: 'Коперника, 9',
    pricePerNight: 1700,
    rating: 4.6,
    guests: 4,
    bedrooms: 2,
    amenities: ['Wi-Fi', 'Кухня', 'Праска'],
    images: ['https://picsum.photos/seed/offer15/600/400'],
    ownerId: 'owner-8',
    isActive: true,
    type: 'apartment',
    highlights: ['Безкоштовна відміна'],
    reviews: [],
  },
];

export const mockOffers: Offer[] = baseOffers.map((offer, index) => ({
  ...offer,
  owner: ownerProfiles[offer.ownerId] ?? defaultOwner(offer.ownerId),
  rooms: offer.rooms ?? defaultRooms(offer, index),
}));

export const mockBookings: Booking[] = [
  {
    id: 'booking-1',
    offerId: 'offer-1',
    userId: 'user-1',
    checkIn: new Date().toISOString(),
    checkOut: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    guests: 2,
    totalPrice: 120 * 3,
    status: 'active',
    paymentType: 'card',
  },
  {
    id: 'booking-2',
    offerId: 'offer-2',
    userId: 'user-1',
    checkIn: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    checkOut: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    guests: 4,
    totalPrice: 90 * 4,
    status: 'pending',
    paymentType: 'cash',
  },
  {
    id: 'booking-3',
    offerId: 'offer-3',
    userId: 'user-1',
    checkIn: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    checkOut: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    guests: 2,
    totalPrice: 150 * 4,
    status: 'completed',
    paymentType: 'online',
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'payment-1',
    bookingId: 'booking-1',
    userId: 'user-1',
    offerId: 'offer-1',
    amount: 360,
    method: 'card',
    status: 'paid',
    date: '2024-03-05',
  },
  {
    id: 'payment-2',
    bookingId: 'booking-2',
    userId: 'user-1',
    offerId: 'offer-2',
    amount: 360,
    method: 'cash',
    status: 'pending',
    date: '2024-03-10',
  },
  {
    id: 'payment-3',
    bookingId: 'booking-3',
    userId: 'user-1',
    offerId: 'offer-3',
    amount: 600,
    method: 'online',
    status: 'failed',
    date: '2024-03-12',
  },
];
