export enum Routes {
  Welcome = 'Welcome',
  Login = 'Login',
  Register = 'Register',
  Auth = 'Auth',
  Main = 'Main',
  SearchResults = 'SearchResults',
  Landmarks = 'Landmarks',
  LandmarksSearchResults = 'LandmarksSearchResults',
  OfferDetails = 'OfferDetails',
  OfferGallery = 'OfferGallery',
  Booking = 'Booking',
  BookingDetails = 'BookingDetails',
  BookingSuccess = 'BookingSuccess',
  PastBookingDetails = 'PastBookingDetails',
  AdminPanel = 'AdminPanel',
  AdminUserDetails = 'AdminUserDetails',
  AdminOfferDetails = 'AdminOfferDetails',
  OwnerObjectForm = 'OwnerObjectForm',
  EditProfile = 'EditProfile',
  PaymentInfo = 'PaymentInfo',
  AddCard = 'AddCard',
  Home = 'Home',
  Notifications = 'Notifications',
  Bookings = 'Bookings',
  Profile = 'Profile',
}
